[workspace]
allow_dirty = false
git_release_enable = true
git_release_type = "prod"
git_release_name = "v{{ version }}"

[[package]]
name = "tyrus_cli"
publish = true

[[package]]
name = "integration_tests"
publish = false
release = false
