[workspace]
allow_dirty = false
publish = false
changelog_update = true
git_release_enable = true
git_release_type = "prod"
git_release_name = "v{{ version }}"

[[package]]
name = "integration_tests"
release = false
changelog_update = false
