[package]
name = "tyrus_di"
version = "0.1.0"
edition = "2021"

[dependencies]
tyrus_common = { path = "../tyrus_common" }
petgraph = "0.6"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
